### PR TITLE
Don't lowercase the key name.

### PR DESCRIPTION
**Pull request by jyoung-asymmetrik**

### CODE REVIEW

**Review by andrewmarcus — COMMENTED** [review]
Ah, so this will lowercase all the keys except `options.name`?  That should be fine.

Does it also handle the case where the 4 parameters are all passed in basically as a single parameter?  By the time it gets to this code block, have the four parameters already been broken out?

**Comment by Robert-W** [comment]
Looks good to me, I think this should be fine. It should be noted that key names will now be case sensitive

**Review by Robert-W — APPROVED** [review]

**Comment by jyoung-asymmetrik** [comment]
@andrewmarcus I think we kept that and just check if the options object is a string. If it is, then we return `[env.getSecretPrefix()` || '', options].join('/');`.
@Robert-W I believe the original intention was that they are case sensitive. From the first version, I think it doesn't lowercase the name.

**Comment by Sieabah** [comment]
The original purpose is that the original keystring besides the name is case insensitive as you can input these differently into config files and they're all equally valid.

**Pull request merged**
